import { createOpenAI } from '@ai-sdk/openai';
import { streamText, tool } from 'ai';
import { z } from 'zod';

// We map OpenRouter to OpenAI SDK
const openrouter = createOpenAI({
  baseURL: 'https://openrouter.ai/api/v1',
  // You should store this in your .env.local file: OPENROUTER_API_KEY="..."
  apiKey: process.env.OPENROUTER_API_KEY || "dummy_key", 
});

export const maxDuration = 30;

export async function POST(req: Request) {
  const { messages } = await req.json();

  const result = streamText({
    model: openrouter('z-ai/glm-4.5-air:free'), // Free OpenRouter model for demo
    messages,
    system: `You are the Axora shopping assistant. You help users find products, specifically home appliances and watches. 
    If a user asks about "home appliances" or "watches", you MUST use the showProduct tool to display relevant products to them. 
    Be polite, concise, and helpful.`,
    tools: {
      showProduct: tool({
        description: 'Show a specific product card to the user. Call this when the user asks for watches, home appliances, or specific items.',
        parameters: z.object({
          category: z.enum(['watches', 'home-appliances', 'other']).describe('The category of the product'),
          productName: z.string().describe('The specific name of the product to show'),
          price: z.number().describe('The price of the product'),
          description: z.string().describe('Short description of the product'),
          image: z.string().optional().describe('URL to the product image')
        }),
        execute: async ({ category, productName, price, description, image }) => {
          // Provide some default images if none generated by the model
          const fallbackImage = category === 'watches' 
            ? 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=600&auto=format&fit=crop' 
            : 'https://images.unsplash.com/photo-1581092921461-7031e4bf0e5e?q=80&w=600&auto=format&fit=crop';
          
          return {
            category,
            productName,
            price,
            description,
            image: image || fallbackImage,
            status: 'success'
          };
        }
      })
    },
    maxSteps: 5, // Allow the model to call the tool and then respond
  });

  return result.toDataStreamResponse();
}
